options:
  formatter: stylish
  merge-default-rules: false
rules:
  border-zero: 1
  brace-style:
    - 1
    - allow-single-line: true
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  clean-import-paths:
    - 1
    - filename-extension: false
      leading-underscore: false
  empty-line-between-blocks:
    - 0
    - ignore-single-line-rulesets: true
  extends-before-declarations: 0
  extends-before-mixins: 0
  final-newline:
    - 1
    - include: true
  force-attribute-nesting: 0
  force-element-nesting: 0
  force-pseudo-nesting: 0
  function-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  hex-length:
    - 1
    - style: short
  hex-notation:
    - 1
    - style: lowercase
  id-name-format:
    - 0
    - convention: hyphenatedlowercase
  indentation:
    - 1
    - size: 2
  leading-zero:
    - 0
    - include: false
  mixin-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  mixins-before-declarations: 0
  nesting-depth: 0
  no-color-keyword: 1
  no-color-literals: 0
  no-css-comments: 1
  no-debug: 1
  no-duplicate-properties:
    - 1
    - exclude: []
  no-empty-rulesets: 1
  no-ids: 1
  no-important: 0
  no-invalid-hex: 1
  no-mergeable-selectors: 0
  no-misspelled-properties:
    - 1
    - extra-properties:
        - composes
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false
  no-trailing-zero: 1
  no-url-protocols: 1
  placeholder-in-extend: 0
  placeholder-name-format:
    - 0
    - convention: hyphenatedlowercase
  property-sort-order:
    - 1
    - ignore-custom-properties: false
      order:
        - $variable
        - $extend
        - $include
        - composes
        - position
        - top
        - right
        - bottom
        - left
        - z-index
        - '-webkit-box-sizing'
        - '-moz-box-sizing'
        - box-sizing
        - display
        - float
        - width
        - min-width
        - max-width
        - height
        - min-height
        - max-height
        - flex
        - flex-align
        - flex-direction
        - flex-flow
        - flex-grow
        - flex-order
        - flex-pack
        - flex-wrap
        - align-content
        - align-items
        - justify-content
        - padding
        - padding-top
        - padding-right
        - padding-bottom
        - padding-left
        - margin
        - margin-top
        - margin-right
        - margin-bottom
        - margin-left
        - overflow
        - overflow-x
        - overflow-y
        - '-webkit-overflow-scrolling'
        - '-ms-overflow-x'
        - '-ms-overflow-y'
        - '-ms-overflow-style'
        - clip
        - clear
        - font
        - font-family
        - font-size
        - font-style
        - font-weight
        - font-variant
        - font-size-adjust
        - font-stretch
        - font-effect
        - font-emphasize
        - font-emphasize-position
        - font-emphasize-style
        - font-smooth
        - '-webkit-hyphens'
        - '-moz-hyphens'
        - hyphens
        - line-height
        - color
        - text-align
        - '-webkit-text-align-last'
        - '-moz-text-align-last'
        - '-ms-text-align-last'
        - text-align-last
        - text-emphasis
        - text-emphasis-color
        - text-emphasis-style
        - text-emphasis-position
        - text-decoration
        - text-indent
        - text-justify
        - text-outline
        - '-ms-text-overflow'
        - text-overflow
        - text-overflow-ellipsis
        - text-overflow-mode
        - text-shadow
        - text-transform
        - text-wrap
        - '-webkit-text-size-adjust'
        - '-ms-text-size-adjust'
        - letter-spacing
        - '-ms-word-break'
        - word-break
        - word-spacing
        - '-ms-word-wrap'
        - word-wrap
        - '-moz-tab-size'
        - '-o-tab-size'
        - tab-size
        - white-space
        - vertical-align
        - list-style
        - list-style-position
        - list-style-type
        - list-style-image
        - pointer-events
        - '-ms-touch-action'
        - touch-action
        - cursor
        - visibility
        - zoom
        - table-layout
        - empty-cells
        - caption-side
        - border-spacing
        - border-collapse
        - content
        - quotes
        - counter-reset
        - counter-increment
        - resize
        - '-webkit-user-select'
        - '-moz-user-select'
        - '-ms-user-select'
        - '-o-user-select'
        - user-select
        - nav-index
        - nav-up
        - nav-right
        - nav-down
        - nav-left
        - background
        - background-color
        - background-image
        - "-ms-filter:\\'progid:DXImageTransform.Microsoft.gradient"
        - 'filter:progid:DXImageTransform.Microsoft.gradient'
        - 'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader'
        - filter
        - background-repeat
        - background-attachment
        - background-position
        - background-position-x
        - background-position-y
        - '-webkit-background-clip'
        - '-moz-background-clip'
        - background-clip
        - background-origin
        - '-webkit-background-size'
        - '-moz-background-size'
        - '-o-background-size'
        - background-size
        - border
        - border-color
        - border-style
        - border-width
        - border-top
        - border-top-color
        - border-top-style
        - border-top-width
        - border-right
        - border-right-color
        - border-right-style
        - border-right-width
        - border-bottom
        - border-bottom-color
        - border-bottom-style
        - border-bottom-width
        - border-left
        - border-left-color
        - border-left-style
        - border-left-width
        - border-radius
        - border-top-left-radius
        - border-top-right-radius
        - border-bottom-right-radius
        - border-bottom-left-radius
        - '-webkit-border-image'
        - '-moz-border-image'
        - '-o-border-image'
        - border-image
        - '-webkit-border-image-source'
        - '-moz-border-image-source'
        - '-o-border-image-source'
        - border-image-source
        - '-webkit-border-image-slice'
        - '-moz-border-image-slice'
        - '-o-border-image-slice'
        - border-image-slice
        - '-webkit-border-image-width'
        - '-moz-border-image-width'
        - '-o-border-image-width'
        - border-image-width
        - '-webkit-border-image-outset'
        - '-moz-border-image-outset'
        - '-o-border-image-outset'
        - border-image-outset
        - '-webkit-border-image-repeat'
        - '-moz-border-image-repeat'
        - '-o-border-image-repeat'
        - border-image-repeat
        - outline
        - outline-width
        - outline-style
        - outline-color
        - outline-offset
        - '-webkit-box-shadow'
        - '-moz-box-shadow'
        - box-shadow
        - 'filter:progid:DXImageTransform.Microsoft.Alpha(Opacity'
        - "-ms-filter:\\'progid:DXImageTransform.Microsoft.Alpha"
        - opacity
        - '-ms-interpolation-mode'
        - '-webkit-transition'
        - '-moz-transition'
        - '-ms-transition'
        - '-o-transition'
        - transition
        - '-webkit-transition-delay'
        - '-moz-transition-delay'
        - '-ms-transition-delay'
        - '-o-transition-delay'
        - transition-delay
        - '-webkit-transition-timing-function'
        - '-moz-transition-timing-function'
        - '-ms-transition-timing-function'
        - '-o-transition-timing-function'
        - transition-timing-function
        - '-webkit-transition-duration'
        - '-moz-transition-duration'
        - '-ms-transition-duration'
        - '-o-transition-duration'
        - transition-duration
        - '-webkit-transition-property'
        - '-moz-transition-property'
        - '-ms-transition-property'
        - '-o-transition-property'
        - transition-property
        - transform-style
        - '-webkit-transform'
        - '-moz-transform'
        - '-ms-transform'
        - '-o-transform'
        - transform
        - '-webkit-transform-origin'
        - '-moz-transform-origin'
        - '-ms-transform-origin'
        - '-o-transform-origin'
        - transform-origin
        - '-webkit-animation'
        - '-moz-animation'
        - '-ms-animation'
        - '-o-animation'
        - animation
        - '-webkit-animation-name'
        - '-moz-animation-name'
        - '-ms-animation-name'
        - '-o-animation-name'
        - animation-name
        - '-webkit-animation-duration'
        - '-moz-animation-duration'
        - '-ms-animation-duration'
        - '-o-animation-duration'
        - animation-duration
        - '-webkit-animation-play-state'
        - '-moz-animation-play-state'
        - '-ms-animation-play-state'
        - '-o-animation-play-state'
        - animation-play-state
        - '-webkit-animation-timing-function'
        - '-moz-animation-timing-function'
        - '-ms-animation-timing-function'
        - '-o-animation-timing-function'
        - animation-timing-function
        - '-webkit-animation-delay'
        - '-moz-animation-delay'
        - '-ms-animation-delay'
        - '-o-animation-delay'
        - animation-delay
        - '-webkit-animation-iteration-count'
        - '-moz-animation-iteration-count'
        - '-ms-animation-iteration-count'
        - '-o-animation-iteration-count'
        - animation-iteration-count
        - '-webkit-animation-direction'
        - '-moz-animation-direction'
        - '-ms-animation-direction'
        - '-o-animation-direction'
        - animation-direction
        - backface-visibility
        - will-change
        - fill
  quotes:
    - 1
    - style: double
  shorthand-values: 1
  single-line-per-selector: 0
  space-after-bang:
    - 1
    - include: false
  space-after-colon: 1
  space-after-comma: 0
  space-before-bang:
    - 1
    - include: true
  space-before-brace:
    - 1
    - include: true
  space-before-colon: 1
  space-between-parens:
    - 1
    - include: false
  trailing-semicolon: 1
  url-quotes: 1
  variable-name-format:
    - 1
    - allow-leading-underscore: true
      convention: hyphenatedlowercase
  zero-unit: 1
