import './commons';

export default {
  Autocomplete: require('./autocomplete'),
  Button: require('./button'),
  Card: require('./card'),
  Checkbox: require('./checkbox'),
  DatePicker: require('./date_picker'),
  Dialog: require('./dialog'),
  Drawer: require('./drawer'),
  Dropdown: require('./dropdown'),
  FontIcon: require('./font_icon'),
  Form: require('./form'),
  Input: require('./input'),
  Link: require('./link'),
  List: require('./list/list'),
  ListItem: require('./list/item'),
  ListDivider: require('./list/divider'),
  ListCheckbox: require('./list/checkbox'),
  ListSubHeader: require('./list/subheader'),
  Menu: require('./menu/menu'),
  MenuItem: require('./menu/menu_item'),
  MenuDivider: require('./menu/menu_divider'),
  IconMenu: require('./menu/icon_menu'),
  Navigation: require('./navigation'),
  ProgressBar: require('./progress_bar'),
  RadioGroup: require('./radio/radio_button'),
  RadioButton: require('./radio/radio_group'),
  Ripple: require('./ripple'),
  Slider: require('./slider'),
  Switch: require('./switch'),
  Tab: require('./tabs/tab'),
  Tabs: require('./tabs/tabs'),
  TimePicker: require('./time_picker')
};
